name: Build Pipeline

trigger:
  branches:
    include:
     - fix/azure-pipelines
  paths:
    exclude:
    - '*.md'
    - 'backends/*'
    - 'images/*'
    - '.github/*'

pool:
  vmImage: 'ubuntu-20.04'

stages:
- template: stages/ci.yaml
