trigger:
  branches:
    include:
    - main

pr: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: ci
    displayName: 'Continuous Integration'
    variables:
    - template: ./templates/iac-variables.yml
    jobs:
    - job: Publish_Artifacts
      steps:
      - task: PublishBuildArtifacts@1
        inputs:
          artifactName: '$(ciArtifactName)'
          pathToPublish: '$(System.DefaultWorkingDirectory))'