---
sections:
  show:
    - header
    - inputs
    - outputs

sort:
  enabled: true
  by: required

content: |
  {{ .Header }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ## Usage Example 

  ``` hcl
  {{ include "example/main.tf" }}
  ```
