stages:
- stage: CIStage
  displayName: Continuous Integration
  variables:
    - group: -mvpconf21-vars
  jobs:
  - job: InicializacaoTerraform
    displayName: Teste de Inicialização Terraform
    steps:
      - bash: |
          cd terraform/stacks/mvpconf21
          export ARM_CLIENT_ID=$(ARM-CLIENT-ID)
          export ARM_CLIENT_SECRET=$(ARM-CLIENT-SECRET)
          export ARM_TENANT_ID=$(ARM-TENANT-ID)
          export ARM_SUBSCRIPTION_ID=$(ARM-SUBSCRIPTION-ID)
          az login --service-principal -u $(ARM-CLIENT-ID) -p $(ARM-CLIENT-SECRET) -t $(ARM-TENANT-ID)
          terraform init -reconfigure \
            -backend-config="resource_group_name=$TF_BACKEND_RESOURCE_GROUP" \
            -backend-config="storage_account_name=$TF_BACKEND_STORAGE_ACCOUNT" \
            -backend-config="container_name=$TF_BACKEND_CONTAINER" \
            -backend-config="key=$TF_BACKEND_KEY" \
          
        displayName: Terraform Init
        env:
          ARM_CLIENT_ID:                $(ARM-CLIENT-ID)
          ARM_CLIENT_SECRET:            $(ARM-CLIENT-SECRET)
          ARM_TENANT_ID:                $(ARM-TENANT-ID)
          TF_BACKEND_STORAGE_ACCOUNT:   $(TF-BACKEND-STORAGE-ACCOUNT)
          TF_BACKEND_RESOURCE_GROUP:    $(TF-BACKEND-RESOURCE-GROUP)
          ARM_SUBSCRIPTION_ID:          $(ARM-SUBSCRIPTION-ID)
          TF_BACKEND_CONTAINER:         $(TF-BACKEND-CONTAINER)
          TF_BACKEND_KEY:               $(TF-BACKEND-KEY)
  - job: Validateterraform
    dependsOn: InicializacaoTerraform
    displayName: Validação do Código
    steps:
      - bash: |
          cd terraform/stacks/mvpconf21
          export ARM_CLIENT_ID=$(ARM-CLIENT-ID)
          export ARM_CLIENT_SECRET=$(ARM-CLIENT-SECRET)
          export ARM_TENANT_ID=$(ARM-TENANT-ID)
          export ARM_SUBSCRIPTION_ID=$(ARM-SUBSCRIPTION-ID)
          az login --service-principal -u $(ARM-CLIENT-ID) -p $(ARM-CLIENT-SECRET) -t $(ARM-TENANT-ID)
          terraform init -reconfigure \
            -backend-config="resource_group_name=$TF_BACKEND_RESOURCE_GROUP" \
            -backend-config="storage_account_name=$TF_BACKEND_STORAGE_ACCOUNT" \
            -backend-config="container_name=$TF_BACKEND_CONTAINER" \
            -backend-config="key=$TF_BACKEND_KEY" \
            terraform validate
            terraform fmt -check -diff
        displayName: Validação do código e identação
        env:
          ARM_CLIENT_ID:                $(ARM-CLIENT-ID)
          ARM_CLIENT_SECRET:            $(ARM-CLIENT-SECRET)
          ARM_TENANT_ID:                $(ARM-TENANT-ID)
          TF_BACKEND_STORAGE_ACCOUNT:   $(TF-BACKEND-STORAGE-ACCOUNT)
          ARM_SUBSCRIPTION_ID:          $(ARM-SUBSCRIPTION-ID)
          TF_BACKEND_RESOURCE_GROUP:    $(TF-BACKEND-RESOURCE-GROUP)
          TF_BACKEND_CONTAINER:         $(TF-BACKEND-CONTAINER)
          TF_BACKEND_KEY:               $(TF-BACKEND-KEY)
  - job: Terraformplan
    dependsOn: Validateterraform
    steps:
    - bash: |
          cd terraform/stacks/mvpconf21
          export ARM_CLIENT_ID=$(ARM-CLIENT-ID)
          export ARM_CLIENT_SECRET=$(ARM-CLIENT-SECRET)
          export ARM_TENANT_ID=$(ARM-TENANT-ID)
          export ARM_SUBSCRIPTION_ID=$(ARM-SUBSCRIPTION-ID)
          az login --service-principal -u $(ARM-CLIENT-ID) -p $(ARM-CLIENT-SECRET) -t $(ARM-TENANT-ID)
          terraform init -reconfigure \
            -backend-config="resource_group_name=$TF_BACKEND_RESOURCE_GROUP" \
            -backend-config="storage_account_name=$TF_BACKEND_STORAGE_ACCOUNT" \
            -backend-config="container_name=$TF_BACKEND_CONTAINER" \
            -backend-config="key=$TF_BACKEND_KEY" \
      displayName: Inicializando
      env:
        ARM_CLIENT_ID:                $(ARM-CLIENT-ID)
        ARM_CLIENT_SECRET:            $(ARM-CLIENT-SECRET)
        ARM_TENANT_ID:                $(ARM-TENANT-ID)
        TF_BACKEND_STORAGE_ACCOUNT:   $(TF-BACKEND-STORAGE-ACCOUNT)
        ARM_SUBSCRIPTION_ID:          $(ARM-SUBSCRIPTION-ID)
        TF_BACKEND_RESOURCE_GROUP:    $(TF-BACKEND-RESOURCE-GROUP)
        TF_BACKEND_CONTAINER:         $(TF-BACKEND-CONTAINER)
        TF_BACKEND_KEY:               $(TF-BACKEND-KEY)
    - task: TerraformCLI@0
      inputs: 
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/stacks/mvpconf21'
        environmentServiceName: 'brbb-sp-terraform-azdevops'
        commandOptions: '-var-file=../env/dev.tfvars'
        allowTelemetryCollection: true
        publishPlanResults: 'Terraform Plan'
      displayName: Terraform Plan      
- stage: Validation
  dependsOn: "CIStage"
  displayName: "Approval or Reject"
  variables:
    - group: -mvpconf21-vars
  jobs: 
  - job: waitForValidation
    displayName: "Wait for manual approval"
    pool: "server"
    timeoutInMinutes: "4320" # job times out in 3 days
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        notifyUsers: |
          carlos.oliveira@softwareone.com
        instructions: "There are resources being destroyed as part of this deployment, please review the output of Terraform plan before approving."
        onTimeout: "reject"
